ClientEvents.lang("en_us", event => {
    // Renaming Some Items
    event.renameItem('smokingstuff:crushed_magical_herb', 'Crushed Herb')
    event.renameItem('smokingstuff:crushed_magical_herb_fire_resistance', 'Pyromancer\'s Herb Blend')
    event.renameItem('smokingstuff:crushed_magical_herb_agility', 'Spry Herb Blend')
    event.renameItem('smokingstuff:crushed_magical_herb_golden', 'Apotheosis Herb Blend')
    event.renameItem('smokingstuff:crushed_magical_herb_hard', 'Wizard Weed Herb Blend')
    event.renameItem('smokingstuff:crushed_magical_herb_invisibility', 'Etherial Herb Blend')
    event.renameItem('smokingstuff:crushed_magical_herb_regen', 'Neb\'s Herb Blend')
    event.renameItem('smokingstuff:crushed_magical_herb_instant_healing', 'Medicinal Herb Blend')
    event.renameItem('smokingstuff:crushed_magical_herb_night_vision', 'Light Head Herb Blend')
    event.renameItem('smokingstuff:crushed_magical_herb_speed', 'Warp Speed Herb Blend')
    event.renameItem('smokingstuff:crushed_magical_herb_strength', 'Gym Bro Herb Blend')
    event.renameItem('smokingstuff:crushed_magical_herb_water_breathing', 'Tide King Herb Blend')

    event.renameItem('smokingstuff:big_magic_tube', 'Thick Nail')
    event.renameItem('smokingstuff:magic_tube', 'Nail')
    event.renameItem('smokingstuff:magic_tube_fire_resistance', 'Pyromancer Nail')
    event.renameItem('smokingstuff:magic_tube_agility', 'Spry Nail')
    event.renameItem('smokingstuff:magic_tube_golden', 'Apotheosis Nail')
    event.renameItem('smokingstuff:magic_tube_hard', 'Wizard Weed Nail')
    event.renameItem('smokingstuff:magic_tube_invisibility', 'Etherial Nail')
    event.renameItem('smokingstuff:magic_tube_regen', 'Neb\'s Nail')
    event.renameItem('smokingstuff:magic_tube_instant_healing', 'Medicinal Nail')
    event.renameItem('smokingstuff:magic_tube_night_vision', 'Light Head Nail')
    event.renameItem('smokingstuff:magic_tube_speed', 'Warp Speed Nail')
    event.renameItem('smokingstuff:magic_tube_strength', 'Gym Bro Nail')
    event.renameItem('smokingstuff:magic_tube_water_breathing', 'Tide King Nail')

    event.renameItem('smokingstuff:gold_magic_paper', 'Gold Leaf')

    event.renameItem('smokingstuff:magic_tube_gold', 'Premium Nail')
    event.renameItem('smokingstuff:magic_tube_fire_resistance_gold', 'Premium Pyromancer Nail')
    event.renameItem('smokingstuff:magic_tube_agility_gold', 'Premium Spry Nail')
    event.renameItem('smokingstuff:magic_tube_golden_gold', 'Premium Apotheosis Nail')
    event.renameItem('smokingstuff:magic_tube_hard_gold', 'Premium Wizard Weed Nail')
    event.renameItem('smokingstuff:magic_tube_invisibility_gold', 'Premium Etherial Nail')
    event.renameItem('smokingstuff:magic_tube_regen_gold', 'Premium Neb\'s Nail')
    event.renameItem('smokingstuff:magic_tube_instant_healing_gold', 'Premium Medicinal Nail')
    event.renameItem('smokingstuff:magic_tube_night_vision_gold', 'Premium Light Head Nail')
    event.renameItem('smokingstuff:magic_tube_speed_gold', 'Premium Warp Speed Nail')
    event.renameItem('smokingstuff:magic_tube_strength_gold', 'Premium Gym Bro Nail')
    event.renameItem('smokingstuff:magic_tube_water_breathing_gold', 'Premium Tide King Nail')
})